### ISSUE TITLE
Integrating pineappl

### ISSUE THREAD

**Issue by scarrazza** [N3PDF/pdfflow#31]
I have just finalized the python interface for pineappl:

https://github.com/N3PDF/pineappl/tree/master/wrappers/python

I think would be interesting to implement the Drell-Yan photon-photon production:

https://github.com/N3PDF/pineappl/blob/master/examples/python-dy-aa/main.py

using vegasflow and then integrate the convolution using pdfflow.

**Comment by scarlehoff** [comment]
Under preparation https://github.com/N3PDF/vegasflow/pull/56

We might want to copy the example to this repo as well once it is finished or just link it to the docs.

**Comment by scarlehoff** [comment]
Done [at vegasflow](https://github.com/N3PDF/vegasflow/blob/master/examples/example_pineappl.py)
