### ISSUE TITLE
Switch on/off LogOutput && Multi-replicas computation

### ISSUE THREAD

**Issue by Radonirinaunimi** [N3PDF/pdfflow#33]
Apologies if I combine the following issues (requests) in one, but on the other hand, I do not think these require two separate issues.

- It would be nice to have some kind of <kbd>Verbose</kbd> that switches on/off the log output here (for instance):
https://github.com/N3PDF/pdfflow/blob/96a6668e294049645db2cca94bacdc99a7018729/src/pdfflow/pflow.py#L168
This would be helpful when loading multiple set of replicas.

- It would also be incredibly useful to have something like: (1) <kbd>mkPDFs</kbd> that loads all the PDF sets at once, and (2) <kbd>xfxQ2s</kbd> that computes a three-dimensional grid of `(rep, pid, x)`-points. This is because, doing the following (see below) becomes expensive for large number of replicas.
```python
for rep in replicas:
     res = rep.xfxQ2(pids, xgrid, q2scale)
    ...
```
On my computer, I could not generate a grid of 1000 replicas as it gets terminated by a SIGKILL error. I saw that there was some discussions in #19 but just wanted a separate issue :sweat_smile: .

**Comment by scarlehoff** [comment]
The thing about the multimember loading I'm working on it right now because it would really be quite useful.

With respect to the other point, since we are using `logger` everywhere (or should be, there might be places where we forgot) you can change the logging level globally at any point:

```python
import logging
logger_pdfflow = logging.getLogger('pdfflow')
logger_pdfflow.setLevel(logging.WARNING)
```

This should remove all `info` logs.

**Comment by Radonirinaunimi** [comment]
> The thing about the multimember loading I'm working on it right now because it would really be quite useful.

Awesome, this would be quite useful indeed.

> This should remove all info logs.

Right, this is definitely the way to go (although there might be useful log.info that is hidden by this).

**Comment by scarlehoff** [comment]
> Right, this is definitely the way to go (although there might be useful log.info that is hidden by this).

Well, in theory with this it only hides the `INFO` from pdfflow (anything else requires knowing beforehand what is the useful info which could also change from person to person so it's... difficult).

**Comment by scarlehoff** [comment]
Both things should be now implemented @Radonirinaunimi

**Comment by Radonirinaunimi** [comment]
Thanks! Awesome, I will try it.
