### ISSUE TITLE
Wrong Uncertainties on performance benchmark 

### ISSUE THREAD

**Issue by marcorossi5** [N3PDF/pdfflow#45]
### Description

There could be an issue with the performance benchmark statistics. The problem relies in the following lines of code

### Code example

https://github.com/N3PDF/pdfflow/blob/b5f608ceda1fb55adf3a3be63c4b321fe4e5dca6/benchmarks/compare_performance_lhapdf.py#L141-L146

### Additional information

The thing is in order to give the uncertainties on this numbers in the plots I missed to dived by sqrt of the number of experiments.

We provided just 10 experiments, then the bars should be smaller by just a factor of three. They where almost invisible, so this wouldn't be a big issue in the plots.

I propose to include from now the correction factor.
Let me know what you think, thanks.

**Comment by scarrazza** [comment]
Ok, please update the code so we can rerun the plot.
