### ISSUE TITLE
PDF sets management

### ISSUE THREAD

**Issue by scarlehoff** [N3PDF/pdfflow#52]
At the moment we are relying on LHAPDF for the whole server/set/organization management. I don't think we really want to reimplement the whole thing, but it would be nice to have at least some feature that is able to download PDFs to `/usr/share/pdfflow` or even `/usr/share/LHAPDF` so that the library can work stand-alone-y.

**Comment by scarlehoff** [comment]
@scarrazza what should we do about this? I was thinking it might make sense to make a fork of LHAPDF with only the set management stuff (maybe open an issue in [their repo](https://gitlab.com/hepcedar/lhapdf)) so it can be distributed via pip.
I think reimplementing the stuff ourselves is both unnecessary extra work and sort of ugly if we are going to be using their servers...

**Comment by scarrazza** [comment]
As discussed, let's open an issue in LHAPDF and request for support.

**Comment by scarlehoff** [comment]
Done https://gitlab.com/hepcedar/lhapdf/-/issues/4

**Comment by scarlehoff** [comment]
We got no answer so I would do two things:

1. Add a mechanism so that one can point to a directory with an environment variable and get the PDFs from there.
2. Do our own (maybe vp-like once NNPDF4.0 is open sourced)

**Comment by scarlehoff** [comment]
This is now halfdone https://gitlab.com/hepcedar/lhapdf/-/merge_requests/12
