### ISSUE TITLE
Add possibility to query (x,Q) arrays in the C/Fortran examples

### ISSUE THREAD

**Issue by scarrazza** [N3PDF/pdfflow#60]
As the title says.

**Comment by scarlehoff** [comment]
As I said earlier, don't really have the appetite (or incentives) to work on this but in this branch there's a minimal example that does that: https://github.com/N3PDF/pdfflow/tree/vectorized_example

If someone is interested enough on this such that they would like me to make something more palatable or even usable *gasp*, I'd be happy to oblige, but for the time being there's that.
